### ISSUE TITLE
Just saying thank you.

### ISSUE THREAD

**Issue by Qix-** [ReFreezed/HotParticles#2]
Hey, just leaving a "thank you" here. We're using this tool pretty extensively in our project. The way you've completely self-isolated modules and exports and kept them completely opinionless is really appreciated - writing an importer was super clean and we only have to modify the exported stuff a little bit to work with our image loader.

So far it's been a very reliable utility and I don't think our particle effects would be nearly as beautiful as they are without the help of HotParticles.

So thanks :) Keep up the good work.

**Comment by ReFreezed** [comment]
Thanks for the nice words! I'm glad you find the program useful. :)
