### ISSUE TITLE
Add option to use relative path with particle texture when selecting from file browser

### ISSUE THREAD

**Issue by Qix-** [ReFreezed/HotParticles#3]
I am writing HotParticles support directly into our game's build pipeline, but the problem I'm facing is the texture path. We can certainly use the default particles but any custom particles become tricky to maintain across the team's machines (since the paths are different).

Is there a chance we could instead have the option to "add" a texture to a hotparticles file and for hotparticles to store the texture's contents directly in the file?

**Comment by flamendless** [comment]
For my project i modify the output lua manually like making it a class where i can pass the image itself

**Comment by flamendless** [comment]
Im think of making an output template, but i need to understand the existing templates first

**Comment by Qix-** [comment]
That's what we do too, but the reason I want to do it as a build step is because I don't like storing generated sources in the git repository, and we already have all of the hotparticles files available to us (plus the file format is easy enough to figure out).

**Comment by Qix-** [comment]
Either this, or allow relative paths for the texture path be relative to the hotparticles file (instead of, for instance, the CWD). That might be better since then we wouldn't have duplicated sprites.

EDIT: Actually yeah I think this is the better approach, and I think it'd be easier for someone to implement anyway (just speculating).

**Comment by Qix-** [comment]
Nevermind, I'm wasting your time - you've already thought of this and already support it. 😅

My apologies. Thanks again for a great tool.

**Comment by ReFreezed** [comment]
Relative paths do work already (relative to the .hotparticles file - CWD is never used), unless there's something I don't understand here. The file browser currently always sets paths to the absolute path, so I could add a setting for the file browser specifically to try to give you relative paths whenever possible or something.

Edit: Ah, I should've reloaded the page before commenting. :P

**Comment by Qix-** [comment]
I think that's what made me think you couldn't - the file browser always uses an absolute path. An option would indeed be very handy :)

**Comment by ReFreezed** [comment]
v1.5.1: The file browser can now give back relative paths.

**Comment by Qix-** [comment]
Awesome, works perfectly. We just finished writing the build stage for our .hotparticles files so this came in handy.
