### ISSUE TITLE
Crash on start - undefined PHYSFS symbol

### ISSUE THREAD

**Issue by Psirus** [ReFreezed/HotParticles#4]
First of all, thank you for this, looks great (at least in the screenshots :grin:).

Unfortunately, it doesn't run on my machine (Ubuntu 20.04). I'm using the "universal" download, unpacked it, and then ran `love Hotparticles.love`. This fails with the following error:
```
psirus|Hot Particles» love HotParticles.love 
Running Hot Particles

Error: module:love/physfs:119: /lib/x86_64-linux-gnu/libluajit-5.1.so.2: undefined symbol: PHYSFS_getSearchPath
stack traceback:
	[ C ]: '__index'
	module:love/physfs:119: 'getSearchPaths' (main.lua:3505)
	src/main.gloa:1163: (main.lua:825)
	[ C ]: 'xpcall'
	module:utils:27: field 'load' (main.lua:25)
	src/main.gloa:1083: (main.lua:769)
	[ C ]: 'xpcall'
	module:utils:27: (main.lua:25)
	[ C ]: 'xpcall'
	[Lua]: (boot.lua:793)
	[ C ]: 'xpcall'
	[Lua]: (boot.lua:802)
```

**Comment by ReFreezed** [comment]
Strange. It works for me in Ubuntu 20.04 (through VirtualBox, not that I think that matters). Is your installation of LÖVE 11.3 good?

**Comment by Psirus** [comment]
I had installed Löve from the repositories, and had no problems so far. Now I've tried the AppImage version from the website, and it works, so thanks! Still weird that the Ubuntu version doesn't work. The one from 20.10 also doesn't work, btw.

**Comment by ReFreezed** [comment]
Ok, good you got it working. I'll close the issue for now.
